spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rpl}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rpl}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rpl}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.port=8080
